version: '3.9'

services:
    db:
        image: postgres:15
        restart: always
        env_file:
            - .env
        ports:
            - '5432:5432'
        volumes:
            - pgdata:/var/lib/postgresql/data

    app:
        build: .
        restart: always
        depends_on:
            - db
        ports:
            - '8000:8000'
        volumes:
            - .:/app
        env_file:
            - .env
        command: bash -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000"

volumes:
    pgdata:
