version: '3.9'

services:
    db:
        image: postgres:15
        restart: always
        env_file:
            - .env
        ports:
            - '5432:5432'
        volumes:
            - pgdata:/var/lib/postgresql/data
        healthcheck:
            test: ['CMD-SHELL', 'pg_isready -U $POSTGRES_USER -d $POSTGRES_DB']
            interval: 5s
            timeout: 5s
            retries: 10

    app:
        build: .
        restart: always
        depends_on:
            db:
                condition: service_healthy
        ports:
            - '8000:8000'
        volumes:
            - .:/app
        env_file:
            - .env
        command: >
            bash -c "
                alembic upgrade head &&
                pytest tests/ &&
                uvicorn main:app --host 0.0.0.0 --port 8000
                "

    celery_worker:
        build: .
        restart: always
        depends_on:
            db:
                condition: service_healthy
        volumes:
            - .:/app
        env_file:
            - .env
        command: celery -A tasks.tasks worker --pool=solo --loglevel=info

    celery_beat:
        build: .
        restart: always
        depends_on:
            db:
                condition: service_healthy
        volumes:
            - .:/app
        env_file:
            - .env
        command: celery -A tasks.tasks beat --loglevel=info

volumes:
    pgdata:
